### PR TITLE
Fixed spelling errors in the Readme.md and Fixed sorting layers

### PR DESCRIPTION
**Pull request by HeadClot**
Hello :) /

This is my first commit to a Defold foundation project!

I fixed a spelling error in the readme.md where "Origo should be Origin." and I also fixed sorting issues for detail objects in the editor. Before detail objects were not showing up in the editor due to both the grass layer and layer1 being on the same sorting layer. I have tested this and have ensured that collisions are working and it looks proper in both play mode and in the editor.

I am looking forward to working with defold in the future. 

- Ben

### CODE REVIEW

**Comment by britzl** [comment]
Ben. Thank you for submitting the spelling fix!

The pull request also mentions "Changed the sorting layer for tilemaps". What was the reason for this change?

**Comment by HeadClot** [comment]
> Ben. Thank you for submitting the spelling fix!
> 
> The pull request also mentions "Changed the sorting layer for tilemaps". What was the reason for this change?

Hello :) /

Before the sorting layer change In the editor it would look like this -> image

After the sorting layer change it would look like this - > 
image

Basically what I am trying to say - Is that the sample was broken in the editor view but only in a minor way. It was an easy fix.

**Comment by britzl** [comment]
> Basically what I am trying to say - Is that the sample was broken but only in a minor way. It was an easy fix.

Brilliant. Thank you for the contribution!

**Comment by HeadClot** [comment]
> > Basically what I am trying to say - Is that the sample was broken but only in a minor way. It was an easy fix.
> 
> Brilliant. Thank you for the contribution!

You are very Welcome. Glad I could help :)

**Pull request merged**
